# Generated by Django 5.1.2 on 2024-11-02 16:21

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_post_blog_post_publish_bb7600_idx'),
    ]

    operations = [
        TrigramExtension()
    ]
